export enum NodeShape {
    SQUARE_RECT = 'SQUARE_RECT',
    ROUND_RECT = 'ROUND_RECT',
    RHOMBUS = 'RHOMBUS',
    ROUND = 'ROUND',
    DOCUMENT = 'DOCUMENT',
    PARALLELOGRAM = 'PARALLELOGRAM',
    TRIANGLE = 'TRIANGLE',
    PENTAGON = 'PENTAGON',
    CARD = 'CARD',
    TRAPEZOID = 'TRAPEZOID'
}
